name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, 'epic/**']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "v1.x"

      - name: Check formatting
        run: deno fmt --check

      - name: Check linting
        run: deno lint

      - name: Check types
        run: deno task check:types

      - name: Test
        run: deno task test
