name: Release

on:
  push:
    tags:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "v1.x"

      - name: Build jcli
        run: |
          for i in x86_64-unknown-linux-gnu x86_64-apple-darwin aarch64-apple-darwin
          do
            deno compile -A --target $i -o jcli-$i main.ts
          done

      - name: Release jcli
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            jcli-x86_64-unknown-linux-gnu
            jcli-x86_64-apple-darwin
            jcli-aarch64-apple-darwin
